"""Projet DM covid19.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1wzdfezHAnAEXLYeRVgI6-YRqyQEOyJ8a
"""

import pandas as pd
from matplotlib import pyplot as pit
import numpy as np
from sklearn.model_selection import train_test_split
import seaborn as sn
dataset_Train = pd.read_csv("Coronavirus_Tunisia.csv")
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import metrics
from sklearn.metrics import confusion_matrix,accuracy_score$import pickle
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

data= pd.read_csv("Coronavirus_Tunisia.csv")

figure(num=None, figsize=(10, 10))
plt.hist(dataset_Train['city'])
plt.xlabel('city')
plt.ylabel('case')

stable = dataset_Train[dataset_Train['age']<60]['case'].value_counts()
danger  = dataset_Train[dataset_Train['age']>60]['case'].value_counts()


city = pd.DataFrame([stable, danger])
city.index = ['stable', 'danger']
city.plot(kind = 'bar', stacked = True, figsize = (10,10))




dataset_Train['case'] = dataset_Train['case']/89
dataset_Train['age'] = dataset_Train['age']/83

dummies = ['case' , 'confirmation_date','age', 'gender', 'city', 'symptomatic', 'return_from', 'country']


dataset_Train['case'].dropna()

dataset_Train.case = dataset_Train['case'].map({'danger': 1, 'stable': 0})


X=dataset_Train.loc[:, dataset_Train.columns != 'case']
y=dataset_Train.iloc[:,0]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20 , random_state=0)

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)



pickle.dump(clf, open("model_tree.pkl",'wb'))

model = pickle.load(open("model_tree.pkl",'rb'))

k_fold = KFold(n_splits = 10, shuffle = True, random_state  =0)

tree = tree.DecisionTreeClassifier()
scoring = 'accuracy'
score = cross_val_score(tree, X, y, cv= k_fold, n_jobs=1, scoring=scoring)


forest = RandomForestClassifier()
scoring = 'accuracy'
score = cross_val_score(forest, X, y, cv= k_fold, scoring=scoring)

(np.mean(score))

k_scores = []
for i in range(10,50) :  
    knn = KNeighborsClassifier(n_neighbors = i)
    scoring = 'accuracy'
    score = cross_val_score(knn, X, y, cv = k_fold, scoring = scoring)  
    k_scores.append(np.mean(score))

k_range = range(10, 50)
plt.plot(k_range, k_scores)
plt.xlabel('Value of K for KNN')
plt.ylabel('Cross-Validated Accuracy')

knn_best = KNeighborsClassifier(n_neighbors = 35)

scoring = 'accuracy'

score = cross_val_score(knn_best, X, y, cv = k_fold, n_jobs = 1, scoring = scoring)
print(score)
(np.mean(score))
